### ISSUE TITLE
Unable to apply theme to Gnome Terminal in Fedora 26

### ISSUE THREAD

**Issue by seandjones92** [arcticicestudio/nord-gnome-terminal#12] opened 2017-10-08 00:34 UTC
I'm having some issues with installing this theme. I have verified that the dependencies outlined in the README have been met. When I run the `nord.sh` script I see the following output:

![first-pic](https://user-images.githubusercontent.com/17571045/31312821-08dec0be-ab8c-11e7-9184-2ce1e4f9dd03.png)

After seeing this I found that Fedora 26 uses `gconftool-2` not `gconftool`. So I changed line 87 from:

```
[[ -z "$GCONFTOOL" ]] && GCONFTOOL=gconftool
```
to:
```
[[ -z "$GCONFTOOL" ]] && GCONFTOOL=gconftool-2
```

After making this change I am now seeing the following output:

![second-pic](https://user-images.githubusercontent.com/17571045/31312822-08e0a99c-ab8c-11e7-8cf8-c6c2c413af6e.png)

Is there something I'm missing here? I've never really taken the time to dig into a GTK theme before so I'm pretty lost.

If there's any more information you need from me please let me know.

**Comment by arcticicestudio** [comment] 2017-10-08 17:13
Thanks for your report :+1: 

I'll set up a Fedora 26 virtual box to see what's broken again with these annoying different dependencies on all these distros... :smile:

**Comment by rafifos** [comment] 2017-10-09 06:41
I'm confirming that the same issue happens on a clean install of Artful. (after the gconf2 package was installed)

**Comment by arcticicestudio** [comment] 2017-10-11 11:22
I was able to reproduce it on a fresh install (virtualbox) of Fedora 26 and Ubuntu 17.10. I think the actual problem is a bug in `dconf`. [This expression](https://github.com/arcticicestudio/nord-gnome-terminal/blob/develop/src/sh/nord.sh#L45) in the theme checks if the path `/org/gnome/terminal/legacy/profiles:/` contains any existing profiles. By default there are two keys called `default` and `list` as defined in [`org.gnome.Terminal.gschema.xml`](https://git.gnome.org/browse/gnome-terminal/tree/src/org.gnome.Terminal.gschema.xml#n107). Strangely the command `dconf list /org/gnome/terminal/legacy/profiles:/` returns nothing:

![gh-12-scrot-dconf-list-fresh](https://user-images.githubusercontent.com/7836623/31437579-0af456d2-ae86-11e7-9aec-f674d208f2ca.png)

As soon as a new profile is created the command prints the correct path keys:

![gh-12-scrot-dconf-list-new-profile](https://user-images.githubusercontent.com/7836623/31437629-32ffa050-ae86-11e7-875e-1cb1cfd64a58.png)

If the newly created profile gets deleted again the command suddenly prints the correct path keys:

![gh-12-scrot-dconf-new-profile-deleted](https://user-images.githubusercontent.com/7836623/31437800-cb3453d4-ae86-11e7-9ece-391d7541e9dc.png)

I think this should be reported to the appropriate bug tracker for `dconf` and/or the GNOME Terminal.

The error where is complains about the missing `gconftool` command is caused due to the failing expression described above and the script tries to use the fallback for old versions that used `gconf` as data storage backend.

**Comment by arcticicestudio** [comment] 2017-10-16 13:46
I've reported [#789056][id] to the official GNOME bug tracker for the `dconf` component.

[id]: https://bugzilla.gnome.org/show_bug.cgi?id=789056

**Comment by arcticicestudio** [comment] 2017-10-28 13:13
This issue will be fixed in #13.

**Comment by arcticicestudio** [comment] 2017-10-28 18:16
The PR #14 includes a fix for this problem. It should now work on all distributions when the basic dependencies are installed. The legacy support for GNOME Terminal versions `< 3.8` has been removed since the `gconf` long-time support for in most distributions will end this year anyway, next to the fact that there are no distributions that ship with GNOME `< 3.8`. 

The compatibility with `dconf` has been improved by using the high-level API of `GSettings` instead.

It be nice for some feedback so this can be merged as soon as possible.

**Closed as completed** 2017-10-30 17:56 UTC
Labels: type-bug, Hacktoberfest

**Comment by gorschu** [comment] 2017-11-12 16:33
Late for the feedback - but the rewrite worked fine on a stock vanilla Gnome install on Arch without ever having touched anything in profiles.

**Comment by arcticicestudio** [comment] 2017-11-12 19:42
@azmodude Great, nice to hear that! Thanks for the feedback :+1:
