### ISSUE TITLE
Profile not listed

### ISSUE THREAD

**Issue by ev-agelos** [arcticicestudio/nord-gnome-terminal#3] opened 2017-04-13 06:55 UTC
I ran the nord.sh but could not see the profile listed even after restarting terminal.
Tried to search for it but could not find it even my own profile couldnt find.

I use mint 18.1
Did not know anything about dconf-editor or gconf-editor so i installed both to see my self.
I have 3 profiles now: default, my own and nord.

In dconf i can see the default and my own while in gconf I can see nord(but not the other two)!

I remember reading "migrating profiles on linux mint 18" in my search results while i was searching whats going on so maybe gconf was old way or something and dconf is new? (and i assume u create the profile with the old way thus is not listed in profiles?)

**Comment by bdfish** [comment] 2017-04-13 14:20
debian9 with gnome 3.22.2 has the same problem

**Comment by arcticicestudio** [comment] 2017-04-17 13:51
It seems like these distributions do not manage their dependency policy correctly. I've searched for similar issues and you may need to install the `dconf-tools` ([Mint](https://community.linuxmint.com/software/view/dconf-tools), [Debian](https://packages.debian.org/jessie/dconf-tools)) package.
Maybe you should install all `dconf` related packages like
  - `dconf-gsettings-backend` to ensure *GSettings* compatibility ([Mint](https://community.linuxmint.com/software/view/dconf-gsettings-backend), [Debian](https://packages.debian.org/jessie/dconf-gsettings-backend)
  - ` dconf-cli` to ensure full CLI support ([Mint](https://community.linuxmint.com/software/view/dconf-cli), [Debian](https://packages.debian.org/jessie/dconf-cli))
  - `dconf-service` to ensure D-Bus support for the *GSettings* backend ([Mint](https://community.linuxmint.com/software/view/dconf-service), [Debian](https://packages.debian.org/jessie/dconf-service))

Would be nice if you can test if this fix the problem since I'm running on Arch Linux running GNOME 3.24 which would distort the results. If this does not fix the problem I'll set up some VirtualBox container to investigate the cause.

**Comment by bdfish** [comment] 2017-04-17 14:03
After i install all of dconf-* you list, then run nord.sh, my current profile will be deleted.
then i test this https://github.com/Mayccoll/Gogh ,i have got same result.
So this issue may be caused by debian

**Comment by arcticicestudio** [comment] 2017-04-17 14:27
Sorry to hear that, this should never happen! Are you sure it got deleted or is is only being hidden on the list but still available via the *dconf-editor*?

The *Gogh* project you've linked to [makes use of the same script](https://github.com/Mayccoll/Gogh/blob/master/_apply-colors.sh#L55#L178) code so the script itself can still cause this issue, but the origin issue can be *dconf* which changed its functional behaviour or contains a bug.

I see what I can do to reproduce this.

**Comment by bdfish** [comment] 2017-04-17 14:58
All of themes i installed is visible in dconf-editor ，but they are hidden in gnome-terminal preferences-profiles
Here are two pictures
![screenshot from 2017-04-17 22-50-46](https://cloud.githubusercontent.com/assets/15389690/25092448/54616892-23c0-11e7-8703-a54548adc214.png)
![screenshot from 2017-04-17 22-54-20](https://cloud.githubusercontent.com/assets/15389690/25092562/d3585d40-23c0-11e7-8e97-9026c6a4a4a3.png)

**Comment by bdfish** [comment] 2017-04-17 15:05
It seems that someone else has the same problem
https://github.com/Mayccoll/Gogh/issues/63

**Comment by arcticicestudio** [comment] 2017-04-25 13:02
I've tried to reproduce this problem today, but when I run the script the new profile *Nord* is visible and works fine.
@ev-agelos Can you post which version of the GNOME terminal (GNOME version) is installed on Mint 18? I've tested it successfully for GNOME `3.20`, `3.22.1` and `3.24`.

@bdfish The list of profiles on your screenshot looks strange, all profiles should have UUIDs as name and the Nord theme generates one too, normally it should not be called `:nord`.
Can you please
  1. create a backup of your used profiles
  2. delete all profiles
  3. install the Nord theme via the `nord.sh` script
  4. check if the new created profile name is a random UUID

Maybe Mint 18 changed one of the packages the script depends on like the random UUID generator.

**Comment by ev-agelos** [comment] 2017-04-25 13:07
@arcticicestudio I have gnome 3.18.3, i guess in the next versions it will work out of the box. I managed to copy-paste manually the nord color values etc so I found a workaround.

**Comment by bdfish** [comment] 2017-04-27 03:48
I did what you say,but the result is same, i delete some component of system,maybe issue caused by this, .And  @ev-agelos 's solution is easy and useful,i have given up using `nord.sh`.

**Comment by arcticicestudio** [comment] 2017-07-08 15:27
I'll close this issue for now. I've tried to reproduce this using GNOME Terminal version 3.24.2 and it works fine. It seems like the issue is related to any distribution dependency problems.

**Closed as completed by arcticicestudio** 2017-07-08 15:27 UTC
Labels: type-bug

**Comment by gorschu** [comment] 2017-09-19 11:31
Since people seem to encounter this issue on Debian-based distributions and I just ran into this on a fresh Stretch install...
Apart from installing the various `dconf-*` utilities, the missing UUIDs @bdfish posted result from `uuidgen` not being installed. A quick `apt-get -y install uuid-runtime` later everything worked just fine.

**Comment by arcticicestudio** [comment] 2017-09-19 18:28
@azmodude Thanks for the info, I'll add a note to the documentation that (next to `dconf-tools`) the `uuid-runtime` package must be installed before running the script.

**Comment by gorschu** [comment] 2017-09-20 10:20
@arcticicestudio You're welcome. Thanks for your great colorscheme(s)!

**Comment by arcticicestudio** [comment] 2017-09-30 12:36
The requirements are now documented in #11.

**Comment by arcticicestudio** [comment] 2017-10-11 11:38
> Related to #12

**Comment by arcticicestudio** [comment] 2017-10-28 18:17
The PR #14 includes the fix for this problem. It should now work on all distributions when the basic dependencies are installed. The legacy support for GNOME Terminal versions `< 3.8` has been removed since the `gconf` long-time support for in most distributions will end this year anyway, next to the fact that there are no distributions that ship with GNOME `< 3.8`. 

The compatibility with `dconf` has been improved by using the high-level API of `GSettings` instead.

It be nice for some feedback so this can be merged as soon as possible.
